### ISSUE TITLE
"Deploy to Bluemix" Button

### ISSUE THREAD

**Issue by bradley-holt** [cloudant-labs/location-tracker-nodejs#13]
Consider adding a "Deploy to Bluemix" button.

**Comment by bradley-holt** [comment]
One problem with this is that a database needs to be provisioned, and I don't think this can be automated with the "Deploy to Bluemix" button.

**Comment by mirgray-zz** [comment]
I think this blog post might be helpful. It includes the manifest.yml to trigger the creation of an NoSQLDB backing service.
https://developer.ibm.com/devops-services/2015/02/18/share-code-new-deploy-bluemix-button/

**Comment by bradley-holt** [comment]
Added in 8f6fa3dc7a85391e2a9cb70c4ec68c7aa4349087.
