### ISSUE TITLE
Add info on creating user permissions features

### ISSUE THREAD

**Issue by jessmantaro** [cloudant-labs/location-tracker-nodejs#22]

**Comment by bradley-holt** [comment]
See the new [Managing User Access](https://github.com/cloudant-labs/location-tracker-nodejs/blob/master/tutorial/tutorial.md#managing-user-access) section.

**Comment by jessmantaro** [comment]
Thanks! Looks good. Making some edits, and I have a quick question. Early
on we say that we'll: "update the map to display individual user locations,
rather than one big map of all user locations"

Do we need to add content on changing the map or database too?

Thanks,
Jess

**Comment by bradley-holt** [comment]
Yes, good call. This would be a good opportunity to talk about Cloudant Query. I'll add some info about this.

**Comment by jessmantaro** [comment]
Hi -

So I deployed to bluemix. Very exciting. I see they have a git interface
there that lets you edit code, build, and deploy. Should we talk about that
briefly in addition to the local dev env info?  A little advertising for
these handy features?  Or is it only a dabbler like me who would use that
interface?  ;)  Seems very convenient.

WDYT?  I could add some content around this. Thoughts?

Thanks,
Jess

**Comment by bradley-holt** [comment]
Interesting idea. I prefer using GitHub and a local editor, so hadn't thought of that. If you want to write something up for this, I think it would be a great addition.

**Comment by jessmantaro** [comment]
Yes, I figured most devs would work that way, but may as well mention it.
It's certainly a fast way to play around.  OK.  I'll add that.  Thanks,
Bradley. Have a great night!

**Comment by bradley-holt** [comment]
I added a section on querying locations by user that discusses Cloudant query in c0f11ae4bca8c288932a5548b95fdcefc3115cb6.

**Comment by jessmantaro** [comment]
Looks great. one typo: significant not signification?

Also - maybe map and reduce mention should link to help on views for
clarity.  Just because we're talking about making an actual "map" of a
place.

I can fix these 2 issues, when I commit some edits. Thanks!

Jess
