### ISSUE TITLE
API KEY PERMISSIONS not setting on database

### ISSUE THREAD

**Issue by Esauromano** [cloudant-labs/location-tracker-nodejs#31]
I have been testing this repo since six weeks ago, during that time i created a couple of bluemix account, 
the first one i created 6 weeks ago had until my trial ended a functioning copy of this repository i deployed from the tutorial "deploy to bluemix" button. After that the accounts i created 2 or 3 weeks ago did not have the same luck, the deployment was successful but the web app did not work correctly, the documents with the locations was not uploading the docs to cloudant and the error page appeared. I checked and encounter that the problem relates to the api keys created on the module.exports.putUser on https://github.com/cloudant-labs/location-tracker-nodejs/blob/master/routes/api.js, they are created and some how it execute this on line 33:

 usersDb.insert(user, user._id, function(err, body) {
            if (!err) {
              res.status(201).json({
                ok: true,
                id: user._id,
                rev: body.rev
              });

But the code line 22 that sets the permissions for the api key on the database:

"cloudantService.set_permissions({database:'location-tracker', username:api.key, roles:['_reader', '_writer']}, function(err, result) {..." 

Does not what is supposed to do as you can see on the images below.

![captura de pantalla 2015-07-17 a las 18 36 55](https://cloud.githubusercontent.com/assets/3507113/8759088/f53c5ed6-2cb2-11e5-97d5-8ef9a1182fd2.png)
![captura de pantalla 2015-07-17 a las 18 37 17](https://cloud.githubusercontent.com/assets/3507113/8759089/f53e47c8-2cb2-11e5-8671-abf700a85061.png)

**Comment by bradley-holt** [comment]
Fixed in 4076a089aea6690141a91d4565d3c1daacdf533f.
