### ISSUE TITLE
Location Tracker Part 2 and Part 3 document issues

### ISSUE THREAD

**Issue by yanzhango** [cloudant-labs/location-tracker-nodejs#33]
1)In the document:
 "All the code for this tutorial can be forked from GitHub from this repository". 
click "this repository." and point to a wrong web page.(part 1 location).
2)After download the  locationtracker-angular. Got the error when you run the application:
POST ERROR:{"status":500,"name":"error","message":"VersionError"}.
The PouchDB version need to be changed in index.html as below:

<script src="//cdn.jsdelivr.net/pouchdb/3.3.0/pouchdb.min.js"></script>

3) The document does not have a Windows environment setting. 
4) The commands: "npm install" and "note admin.js db put" do not work. Any steps is missing?
5) The document for finding the "Show Credentials" way that can not find a Credentials.

**Comment by bradley-holt** [comment]
Status of the items in this issue:
1. Fixed.
2. Please open as an issue on the [Location Tracker Angular](https://github.com/cloudant-labs/location-tracker-angular) repository.
3. We will be addressing this in future sample apps, but not this one.
4. Same issue as number 3.
5. Fixed.
