### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by ukmadlz** [cloudant-labs/location-tracker-nodejs#5]
We need to make it obvious in the README.md to inform people where to add usernames and password.

Also, a quick note on how to create API keys for the angular part.

**Comment by ukmadlz** [comment]
I've added a quick route to the node app to generate API keys if you use bluemix. But I can't work out the best way of passing them to the /public/app.js file. Any ideas?

**Comment by bradley-holt** [comment]
It might be helpful if I shared the roadmap…
1. [x] Make this a Node.js app (technically, no real Node.js functionality)
2. [x] Make this deployable to Bluemix
3. [x] Create and bind Cloudant as a Bluemix service
4. [x] Use the Cloudant Node.js client library
5. [x] Move authentication to Node.js

There are currently [instructions in the README](https://github.com/cloudant-labs/location-tracker-nodejs#configuring) for how to configure Cloudant credentials (assuming this is what you were referring to with usernames and password). This will be expanded as necessary if new configuration options are needed.

I haven't touched (or even really looked) _any_ of the code yet in the `public` directory. I'll probably get to that in step 4 or 5. When you say "API keys", do you mean Cloudant API keys or something else? The plan is to have the Node.js app hand out Cloudant API keys to the client side app in step 5.

As for passing API keys to `public/app.js`, I'm not sure yet how that will be done (when I get to step 5). I'll probably serve an API endpoint from the Node.js app that the client app can hit to get its Cloudant API key. The client app will then probably store that API key in a special PouchDB database reserved for configuration settings (and this database _will_ not be replicated with a remote database).

**Comment by bradley-holt** [comment]
In d01e07d65de1be80c80560aad330b813b652cf62, we prepend the origin of the current window to the database URL. The Node.js app then proxies this to Cloudant (with some modifications, where needed). In 8f4ed5e883264f272fe163f170fe149a8fcb89f5, we create a new API key for the user and log the user in, if they are not already logged in.

This is going to be updated to allow the user to register with a username and password when they hit the welcome screen, and then login with those credentials. Logging in will decrypt the user's API key password, which will be used to authenticate them with Cloudant.
